Repository 0soft/mui-form-fields, pull requests merged in 2019-06, with the labels that each got.

#22 Add "dividers" prop on FormDialog
  README.md
  src/components/FormDialog.tsx
  stories/FormDialog.stories.tsx
Labels: enhancement

#23 Add FormSelectField component
  src/components/FormSelectField.tsx
  src/index.ts
  stories/FormSelectField.stories.tsx
  stories/FormTest.tsx
Labels: enhancement

#25 Change "dependencies" badge to "peerDependencies"
  README.md
  package.json
Labels: enhancement

#26 Add FormReactSelectField components
  package-lock.json
  package.json
  src/components/FormReactSelectField.tsx
  src/index.ts
  stories/FormReactSelectField.stories.tsx
  tslint.json
Labels: enhancement

#27 Add "multi" option to FormSelectField and FormReactSelectField
  src/components/FormReactSelectField.tsx
  src/components/FormSelectField.tsx
  stories/FormReactSelectField.stories.tsx
  stories/FormSelectField.stories.tsx
Labels: enhancement

#30 Change building rules to include type definition files
  .gitignore
  .npmignore
  dist/mui-form-fields.js
  dist/mui-form-fields.min.js
  dist/types/components/FormButtonField.d.ts
  dist/types/components/FormChipField.d.ts
  dist/types/components/FormDateField.d.ts
  dist/types/components/FormDateRangeField.d.ts
  dist/types/components/FormDateTimeField.d.ts
  dist/types/components/FormDialog.d.ts
  dist/types/components/FormField.d.ts
  dist/types/components/FormFileUploadField.d.ts
  dist/types/components/FormIntegerField.d.ts
  dist/types/components/FormMoneyField.d.ts
  dist/types/components/FormNumberField.d.ts
  dist/types/components/FormPercentageField.d.ts
  dist/types/components/FormPhoneField.d.ts
  dist/types/components/FormReactSelectField.d.ts
  dist/types/components/FormReadOnlyField.d.ts
  dist/types/components/FormSelectField.d.ts
  dist/types/components/FormShowField.d.ts
  dist/types/components/FormSwitchField.d.ts
  dist/types/components/FormTextField.d.ts
  dist/types/components/FormWeekField.d.ts
  dist/types/components/Pickers/DatePicker.d.ts
  dist/types/components/Pickers/DateRangePicker.d.ts
  dist/types/components/Pickers/DateTimePicker.d.ts
  dist/types/components/Pickers/WeekPicker.d.ts
  dist/types/components/Pickers/index.d.ts
  dist/types/components/Pickers/styles.d.ts
  dist/types/helpers/IntegerMask.d.ts
  dist/types/helpers/MoneyMask.d.ts
  dist/types/helpers/NumberMask.d.ts
  dist/types/helpers/PercentageMask.d.ts
  dist/types/helpers/PhoneMask.d.ts
  dist/types/helpers/index.d.ts
  dist/types/index.d.ts
  dist/types/utils/formatters.d.ts
  dist/types/utils/index.d.ts
  dist/types/utils/parsers.d.ts
  dist/types/utils/validators.d.ts
  package.json
  tsconfig.json
Labels: enhancement

#32 Fix `close` button not closing the FormDialog
  src/components/FormDialog.tsx
Labels: bug

#33 Fix initialValues not being passed through Form on `FormDialog`
  src/components/FormDialog.tsx
Labels: bug

#34 Add some basic Docz pages
  .gitignore
  .npmignore
  babel.config.js
  bin/generateComponentsPages.js
  docz/FormTest.jsx
  docz/ToggleButton.jsx
  docz/components/FormButtonField.mdx
  docz/components/FormChipField.mdx
  docz/components/FormDateField.mdx
  docz/components/FormDateRangeField.mdx
  docz/components/FormDateTimeField.mdx
  docz/components/FormFileUploadField.mdx
  docz/components/FormIntegerField.mdx
  docz/components/FormMoneyField.mdx
  docz/components/FormNumberField.mdx
  docz/components/FormPercentageField.mdx
  docz/components/FormPhoneField.mdx
  docz/components/FormReactSelectField.mdx
  docz/components/FormReadOnlyField.mdx
  docz/components/FormSelectField.mdx
  docz/components/FormShowField.mdx
  docz/components/FormSwitchField.mdx
  docz/components/FormTextField.mdx
  docz/components/FormWeekField.mdx
  docz/getting-started.mdx
  doczrc.js
  package-lock.json
  package.json
  src/components/FormReactSelectField.tsx
  src/components/FormSelectField.tsx
  src/index.ts
  src/utils/index.ts
Labels: enhancement

#35 Some final fixes for 0.0.2
  README.md
  bin/getComponentsTable.js
  dist/mui-form-fields.js
  dist/mui-form-fields.min.js
  dist/types/index.d.ts
  dist/types/utils/index.d.ts
  docz/getting-started.mdx
  netlify.toml
  package.json
  src/utils/index.ts
Labels: bug, enhancement

#39 Do not display header and footer dividers when dividers are not requested
  src/components/FormDialog.tsx
Labels: enhancement

#40 Fix import components on mdx files for read of properties
  README.md
  babel.config.js
  bin/generateComponentsPages.js
  devtools/getComponents.js
  docz/components/FormButtonField.mdx
  docz/components/FormChipField.mdx
  docz/components/FormDateField.mdx
  docz/components/FormDateRangeField.mdx
  docz/components/FormDateTimeField.mdx
  docz/components/FormFileUploadField.mdx
  docz/components/FormIntegerField.mdx
  docz/components/FormMoneyField.mdx
  docz/components/FormNumberField.mdx
  docz/components/FormPercentageField.mdx
  docz/components/FormPhoneField.mdx
  docz/components/FormReactSelectField.mdx
  docz/components/FormReadOnlyField.mdx
  docz/components/FormSelectField.mdx
  docz/components/FormShowField.mdx
  docz/components/FormSwitchField.mdx
  docz/components/FormTextField.mdx
  docz/components/FormWeekField.mdx
  doczrc.js
  package-lock.json
  package.json
  tsconfig.json
Labels: bug

#41 Add missing types.ts file on deployment build
  dist/types/components/Pickers/types.ts
  package.json
Labels: bug

#42 Add google analytics and OGP tags
  docz/index.html
  doczrc.js
  package.json
Labels: enhancement

#43 Add homepage
  package.json
Labels: enhancement

#44 Adds unit tests to validators
  .prettierrc
  package.json
  src/utils/validators.ts
  tests/tslint.json
  tests/utils/validators.ts
  tslint.json
Labels: enhancement

#45 Adds travis ci to run unit tests
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: enhancement
